### ISSUE TITLE
Schema registry not found - invalid url?

### ISSUE THREAD

**Issue by kophi** [rh-marketingops/fluvii#30]
I am using v0.2.14 and get the following error:
> No connection adapters were found for '**httphttp**://kafka-schema-registry:8081/schemas/ids/10'

Environment:
>       TZ: Europe/Zurich
>       FLUVII_KAFKA_BOOTSTRAP_SERVERS: "kafka1:19092"
>       FLUVII_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"

Traceback:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/confluent_kafka/deserializing_consumer.py", line 137, in poll
>     value = self._value_deserializer(value, ctx)
>   File "/usr/local/lib/python3.10/site-packages/confluent_kafka/schema_registry/avro.py", line 357, in __call__
>     schema = self._registry.get_schema(schema_id)
>   File "/usr/local/lib/python3.10/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 368, in get_schema
>     response = self._rest_client.get('schemas/ids/{}'.format(schema_id))
>   File "/usr/local/lib/python3.10/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 124, in get
>     return self.send_request(url, method='GET', query=query)
>   File "/usr/local/lib/python3.10/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 167, in send_request
>     response = self.session.request(
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 695, in send
>     adapter = self.get_adapter(url=request.url)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 792, in get_adapter
>     raise InvalidSchema(f"No connection adapters were found for {url!r}")
> requests.exceptions.InvalidSchema: No connection adapters were found for 'httphttp://kafka-schema-registry:8081/schemas/ids/10'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "//./main.py", line 20, in <module>
>     fluvii_table_app().run()
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_app.py", line 183, in run
>     self._run(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_app.py", line 160, in _run
>     log_and_raise_error(self.metrics_manager, e)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_app.py", line 154, in _run
>     self._app_batch_run_loop(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_table_app.py", line 38, in _app_batch_run_loop
>     super()._app_batch_run_loop(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_app.py", line 122, in _app_batch_run_loop
>     self._handle_message(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_app.py", line 105, in _handle_message
>     self.consume(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/fluvii_app/fluvii_app.py", line 174, in consume
>     self.transaction.consume(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/transaction/transaction.py", line 59, in consume
>     self.message = self.consumer.consume(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/consumer/consumer.py", line 280, in consume
>     return super().consume(timeout=timeout)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/consumer/consumer.py", line 120, in consume
>     self.message = self._poll_for_message(timeout)
>   File "/usr/local/lib/python3.10/site-packages/fluvii/consumer/consumer.py", line 81, in _poll_for_message
>     message = self._consumer.poll(timeout)
>   File "/usr/local/lib/python3.10/site-packages/confluent_kafka/deserializing_consumer.py", line 139, in poll
>     raise ValueDeserializationError(exception=se, kafka_message=msg)
> confluent_kafka.error.ValueDeserializationError: KafkaError{code=_VALUE_DESERIALIZATION,val=-159,str="No connection adapters were found for 'httphttp://kafka-schema-registry:8081/schemas/ids/10'"}

**Comment by truthordata** [comment]
Hey thanks for posting an issue! I'll take a look, though it looks like some sort of parsing error of the url, probably an easy fix.

**Comment by truthordata** [comment]
Fix is live in v0.2.15, please feel free to respond here if you see other related issues, thanks! :)
